services:

  backend:
    container_name: backend
    build: ./backend
    ports:
      - "666:666"
    networks:
      - app-net
  
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "777:777"
    networks:
      - app-net
    depends_on:
      - backend

networks:
  app-net:
    driver: bridge